In [1]:
sales = [3432,3454,3332,2213]
profit = [454,332,344,334]

In [2]:
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.13228438228438227,
 0.09612044006948466,
 0.10324129651860744,
 0.1509263443289652]

In [3]:
import numpy as np

In [5]:
sales_array = np.array(sales)

In [8]:
sales_array

array([3432, 3454, 3332, 2213])

In [7]:
type(sales_array)

numpy.ndarray

In [10]:
profit_array=np.array(profit)

In [11]:
profit_array

array([454, 332, 344, 334])

In [12]:
profit_array/sales_array

array([0.13228438, 0.09612044, 0.1032413 , 0.15092634])

In [13]:
sales*3

[3432, 3454, 3332, 2213, 3432, 3454, 3332, 2213, 3432, 3454, 3332, 2213]

In [14]:
sales_array*3

array([10296, 10362,  9996,  6639])

In [15]:
dict = {'cust_id':1, 'Cust_name':'Rahul','Product':'Python'}

In [16]:
list1 = [(i,j) for i,j in dict.items()]

In [18]:
np.array(list1)

array([['cust_id', '1'],
       ['Cust_name', 'Rahul'],
       ['Product', 'Python']], dtype='<U9')

In [21]:
sales_arr1=sales_array[0:4]

In [24]:
sales_arr1[0]=1000

In [27]:
sales_array[0]=0

In [28]:
sales_arr1

array([   0, 3454, 3332, 2213])

In [29]:
sales_arr2=sales_array.copy()

In [31]:
sales_arr2[0]=1000

In [32]:
sales_arr2

array([1000, 3454, 3332, 2213])

In [33]:
sales_array

array([   0, 3454, 3332, 2213])

In [34]:
list1 = [1,2.4, 'R', True]

In [41]:
type(list1[3])

bool

In [60]:
array1=np.array(list1)

In [63]:
type(array1[1])

numpy.int32

In [59]:
list1 = [1, False]

In [64]:
array1

array([1, 0])

In [68]:
sales_us = [3454,3344,3222,4543]
sales_eu = [5432,2334,3343,2234]
sales_jp = [5543,2234,5443,3222]

In [73]:
sales_matrix=np.array((sales_us,sales_eu,sales_jp))

In [80]:
sales_matrix

array([[3454, 3344, 3222, 4543],
       [5432, 2334, 3343, 2234],
       [5543, 2234, 5443, 3222]])

In [77]:
profit_us = [343,444,545,433]
profit_eu = [544,333,545,334]
profit_jp=  [665,334,344,555]

In [78]:
profit_matrix = np.array([profit_us, profit_eu, profit_jp])

In [79]:
profit_matrix

array([[343, 444, 545, 433],
       [544, 333, 545, 334],
       [665, 334, 344, 555]])

In [82]:
profit_matrix/sales_matrix

array([[0.09930515, 0.13277512, 0.1691496 , 0.09531147],
       [0.10014728, 0.14267352, 0.16302722, 0.14950761],
       [0.11997113, 0.14950761, 0.06320044, 0.17225326]])

In [83]:
sales_matrix

array([[3454, 3344, 3222, 4543],
       [5432, 2334, 3343, 2234],
       [5543, 2234, 5443, 3222]])

In [84]:
rdict = {'US':0, 'EU':1, 'JP':2}
qdict = {'Q1':0, 'Q2':1, 'Q3':2, 'Q4':3}

In [86]:
sales_matrix[rdict['US']][qdict['Q4']]

4543

In [87]:
list1 = np.arange(0,20)

In [88]:
list1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [89]:
list(range(0,20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [96]:
a=np.reshape(list1, (5,4),'C')

In [105]:
np.reshape(list1, (5,4), 'A')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [99]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [98]:
a.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [106]:
list1=['Hello', 'World']

In [107]:
for i in list1:
    print(i)

Hello
World


In [109]:
txt = "welcome to the jungle"

x = txt.split(' ')

print(x)

['welcome', 'to', 'the', 'jungle']


In [116]:
x=int(input())

100


In [119]:
type(x)

int

In [120]:
x=int(input())
y=int(input())
even_no=list(range(x,y,2))
print(even_no)

300
400
[300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398]
